services:
  postgres-test:
    image: postgres:16
    container_name: postgres-test
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata-test:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  liquibase-test:
    build: ./liquibase-migrator
    image: migkit/liquibase-migrator:test
    pull_policy: never
    container_name: liquibase-test
    depends_on:
      postgres-test:
        condition: service_healthy
    restart: "no"
    environment:
      # Main DB
      MAIN_DB_TYPE: postgresql
      MAIN_DB_HOST: postgres-test
      MAIN_DB_PORT: 5432
      MAIN_DB_USER: testuser
      MAIN_DB_PASSWORD: testpass
      MAIN_DB_NAME: testdb

      # Reference DB
      REF_DB_TYPE: postgresql
      REF_DB_HOST: postgres-test
      REF_DB_PORT: 5432
      REF_DB_USER: testuser
      REF_DB_PASSWORD: testpass
      REF_DB_NAME: testdb_ref

      CHANGELOG_FORMAT: sql
      SCHEMA_SCRIPTS: /liquibase/schema/00-init-db.sql,/liquibase/schema/01-init-data.sql,/liquibase/schema/02-triggers.sql 
    volumes:
      - ./sandbox/liquibase-migrator/schema:/liquibase/schema
      - ./sandbox/liquibase-migrator/liquibase.properties:/liquibase/liquibase.properties:ro
      - ./sandbox/liquibase-migrator/changelog:/liquibase/changelog
    # Default command can be overridden when running
    # Examples:
    # --init
    # --generate
    # --update
    # --shell

volumes:
  pgdata-test:
