-- liquibase formatted sql

-- changeset liquibase-user:1757842686010-1 splitStatements:false
CREATE TABLE "public"."users" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "username" VARCHAR(50) NOT NULL, "email" VARCHAR(100) NOT NULL, "first_name" VARCHAR(50), "last_name" VARCHAR(50), "status" VARCHAR(20) DEFAULT 'active', "phone" VARCHAR(20), "last_login" TIMESTAMP WITHOUT TIME ZONE, "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), "middle_name" VARCHAR(50), CONSTRAINT "users_pkey" PRIMARY KEY ("id"));
-- rollback DROP TABLE IF EXISTS "users";

-- changeset liquibase-user:1757842686010-2 splitStatements:false
CREATE TABLE "public"."categories" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR(100) NOT NULL, "description" TEXT, "parent_id" INTEGER, "is_active" BOOLEAN DEFAULT TRUE, "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), CONSTRAINT "categories_pkey" PRIMARY KEY ("id"));
-- rollback DROP TABLE IF EXISTS "categories";

-- changeset liquibase-user:1757842686010-3 splitStatements:false
CREATE TABLE "public"."posts" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "user_id" INTEGER, "category_id" INTEGER, "title" VARCHAR(200) NOT NULL, "slug" VARCHAR(250) NOT NULL, "content" TEXT, "excerpt" TEXT, "status" VARCHAR(20) DEFAULT 'draft', "view_count" INTEGER DEFAULT 0, "featured" BOOLEAN DEFAULT FALSE, "published_at" TIMESTAMP WITHOUT TIME ZONE, "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), "tags" TEXT, CONSTRAINT "posts_pkey" PRIMARY KEY ("id"));
-- rollback DROP TABLE IF EXISTS "posts";

-- changeset liquibase-user:1757842686010-4 splitStatements:false
CREATE TABLE "public"."tags" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR(50) NOT NULL, "color" VARCHAR(7) DEFAULT '#007bff', "description" TEXT, "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), CONSTRAINT "tags_pkey" PRIMARY KEY ("id"));
-- rollback DROP TABLE IF EXISTS "tags";

-- changeset liquibase-user:1757842686010-5 splitStatements:false
CREATE TABLE "public"."comments" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "post_id" INTEGER, "user_id" INTEGER, "parent_id" INTEGER, "content" TEXT NOT NULL, "status" VARCHAR(20) DEFAULT 'approved', "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), CONSTRAINT "comments_pkey" PRIMARY KEY ("id"));
-- rollback DROP TABLE IF EXISTS "comments";

-- changeset liquibase-user:1757842686010-6 splitStatements:false
CREATE TABLE "public"."user_profiles" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "user_id" INTEGER, "bio" TEXT, "avatar_url" VARCHAR(255), "website" VARCHAR(255), "location" VARCHAR(100), "birth_date" date, "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), CONSTRAINT "user_profiles_pkey" PRIMARY KEY ("id"));
-- rollback DROP TABLE IF EXISTS "user_profiles";

-- changeset liquibase-user:1757842686010-7 splitStatements:false
CREATE TABLE "public"."settings" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "key" VARCHAR(100) NOT NULL, "value" TEXT, "description" TEXT, "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), CONSTRAINT "settings_pkey" PRIMARY KEY ("id"));
-- rollback DROP TABLE IF EXISTS "settings";

-- changeset liquibase-user:1757842686010-8 splitStatements:false
CREATE TABLE "public"."notifications" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "user_id" INTEGER, "title" VARCHAR(200) NOT NULL, "message" TEXT, "type" VARCHAR(50) DEFAULT 'info', "is_read" BOOLEAN DEFAULT FALSE, "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), CONSTRAINT "notifications_pkey" PRIMARY KEY ("id"));
-- rollback DROP TABLE IF EXISTS "notifications";

-- changeset liquibase-user:1757842686010-9 splitStatements:false
CREATE TABLE "public"."post_tags" ("post_id" INTEGER NOT NULL, "tag_id" INTEGER NOT NULL, CONSTRAINT "post_tags_pkey" PRIMARY KEY ("post_id", "tag_id"));
-- rollback DROP TABLE IF EXISTS "post_tags";

-- changeset liquibase-user:1757842686010-11 splitStatements:false
ALTER TABLE "public"."users" ADD CONSTRAINT "users_email_key" UNIQUE ("email");
-- rollback -- Rollback: DROP CONSTRAINT "users_email_key" from "users"
-- Note: Skipped due to PostgreSQL limitations with IF EXISTS for constraints

-- changeset liquibase-user:1757842686010-12 splitStatements:false
ALTER TABLE "public"."users" ADD CONSTRAINT "users_username_key" UNIQUE ("username");
-- rollback -- Rollback: DROP CONSTRAINT "users_username_key" from "users"
-- Note: Skipped due to PostgreSQL limitations with IF EXISTS for constraints

-- changeset liquibase-user:1757842686010-17 splitStatements:false
ALTER TABLE "public"."posts" ADD CONSTRAINT "posts_slug_key" UNIQUE ("slug");
-- rollback -- Rollback: DROP CONSTRAINT "posts_slug_key" from "posts"
-- Note: Skipped due to PostgreSQL limitations with IF EXISTS for constraints

-- changeset liquibase-user:1757842686010-18 splitStatements:false
ALTER TABLE "public"."tags" ADD CONSTRAINT "tags_name_key" UNIQUE ("name");
-- rollback -- Rollback: DROP CONSTRAINT "tags_name_key" from "tags"
-- Note: Skipped due to PostgreSQL limitations with IF EXISTS for constraints

-- changeset liquibase-user:1757842686010-23 splitStatements:false
ALTER TABLE "public"."settings" ADD CONSTRAINT "settings_key_key" UNIQUE ("key");
-- rollback -- Rollback: DROP CONSTRAINT "settings_key_key" from "settings"
-- Note: Skipped due to PostgreSQL limitations with IF EXISTS for constraints

-- changeset liquibase-user:1757842686010-28 splitStatements:false
ALTER TABLE "public"."categories" ADD CONSTRAINT "categories_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "public"."categories" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- rollback -- Rollback: DROP CONSTRAINT "categories_parent_id_fkey" from "categories"
-- Note: Skipped due to PostgreSQL limitations with IF EXISTS for constraints

-- changeset liquibase-user:1757842686010-29 splitStatements:false
ALTER TABLE "public"."comments" ADD CONSTRAINT "comments_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "public"."comments" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- rollback -- Rollback: DROP CONSTRAINT "comments_parent_id_fkey" from "comments"
-- Note: Skipped due to PostgreSQL limitations with IF EXISTS for constraints

-- changeset liquibase-user:1757842686010-30 splitStatements:false
ALTER TABLE "public"."comments" ADD CONSTRAINT "comments_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "public"."posts" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- rollback -- Rollback: DROP CONSTRAINT "comments_post_id_fkey" from "comments"
-- Note: Skipped due to PostgreSQL limitations with IF EXISTS for constraints

-- changeset liquibase-user:1757842686010-31 splitStatements:false
ALTER TABLE "public"."comments" ADD CONSTRAINT "comments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- rollback -- Rollback: DROP CONSTRAINT "comments_user_id_fkey" from "comments"
-- Note: Skipped due to PostgreSQL limitations with IF EXISTS for constraints

-- changeset liquibase-user:1757842686010-32 splitStatements:false
ALTER TABLE "public"."notifications" ADD CONSTRAINT "notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- rollback -- Rollback: DROP CONSTRAINT "notifications_user_id_fkey" from "notifications"
-- Note: Skipped due to PostgreSQL limitations with IF EXISTS for constraints

-- changeset liquibase-user:1757842686010-33 splitStatements:false
ALTER TABLE "public"."post_tags" ADD CONSTRAINT "post_tags_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "public"."posts" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- rollback -- Rollback: DROP CONSTRAINT "post_tags_post_id_fkey" from "post_tags"
-- Note: Skipped due to PostgreSQL limitations with IF EXISTS for constraints

-- changeset liquibase-user:1757842686010-34 splitStatements:false
ALTER TABLE "public"."post_tags" ADD CONSTRAINT "post_tags_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "public"."tags" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- rollback -- Rollback: DROP CONSTRAINT "post_tags_tag_id_fkey" from "post_tags"
-- Note: Skipped due to PostgreSQL limitations with IF EXISTS for constraints

-- changeset liquibase-user:1757842686010-35 splitStatements:false
ALTER TABLE "public"."posts" ADD CONSTRAINT "posts_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "public"."categories" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- rollback -- Rollback: DROP CONSTRAINT "posts_category_id_fkey" from "posts"
-- Note: Skipped due to PostgreSQL limitations with IF EXISTS for constraints

-- changeset liquibase-user:1757842686010-36 splitStatements:false
ALTER TABLE "public"."posts" ADD CONSTRAINT "posts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- rollback -- Rollback: DROP CONSTRAINT "posts_user_id_fkey" from "posts"
-- Note: Skipped due to PostgreSQL limitations with IF EXISTS for constraints

-- changeset liquibase-user:1757842686010-37 splitStatements:false
ALTER TABLE "public"."user_profiles" ADD CONSTRAINT "user_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- rollback -- Rollback: DROP CONSTRAINT "user_profiles_user_id_fkey" from "user_profiles"
-- Note: Skipped due to PostgreSQL limitations with IF EXISTS for constraints

-- changeset liquibase-user:1757842686010-10 splitStatements:false
CREATE INDEX "idx_users_status" ON "public"."users" USING btree("status");
-- rollback DROP INDEX IF EXISTS "idx_users_status";

-- changeset liquibase-user:1757842686010-13 splitStatements:false
CREATE INDEX "idx_posts_user_id" ON "public"."posts" USING btree("user_id");
-- rollback DROP INDEX IF EXISTS "idx_posts_user_id";

-- changeset liquibase-user:1757842686010-14 splitStatements:false
CREATE INDEX "idx_posts_category_id" ON "public"."posts" USING btree("category_id");
-- rollback DROP INDEX IF EXISTS "idx_posts_category_id";

-- changeset liquibase-user:1757842686010-15 splitStatements:false
CREATE INDEX "idx_posts_status" ON "public"."posts" USING btree("status");
-- rollback DROP INDEX IF EXISTS "idx_posts_status";

-- changeset liquibase-user:1757842686010-16 splitStatements:false
CREATE INDEX "idx_posts_published_at" ON "public"."posts" USING btree("published_at");
-- rollback DROP INDEX IF EXISTS "idx_posts_published_at";

-- changeset liquibase-user:1757842686010-19 splitStatements:false
CREATE INDEX "idx_comments_post_id" ON "public"."comments" USING btree("post_id");
-- rollback DROP INDEX IF EXISTS "idx_comments_post_id";

-- changeset liquibase-user:1757842686010-20 splitStatements:false
CREATE INDEX "idx_comments_user_id" ON "public"."comments" USING btree("user_id");
-- rollback DROP INDEX IF EXISTS "idx_comments_user_id";

-- changeset liquibase-user:1757842686010-21 splitStatements:false
CREATE INDEX "idx_comments_parent_id" ON "public"."comments" USING btree("parent_id");
-- rollback DROP INDEX IF EXISTS "idx_comments_parent_id";

-- changeset liquibase-user:1757842686010-22 splitStatements:false
CREATE INDEX "idx_user_profiles_user_id" ON "public"."user_profiles" USING btree("user_id");
-- rollback DROP INDEX IF EXISTS "idx_user_profiles_user_id";

-- changeset liquibase-user:1757842686010-24 splitStatements:false
CREATE INDEX "idx_notifications_user_id" ON "public"."notifications" USING btree("user_id");
-- rollback DROP INDEX IF EXISTS "idx_notifications_user_id";

-- changeset liquibase-user:1757842686010-25 splitStatements:false
CREATE INDEX "idx_notifications_is_read" ON "public"."notifications" USING btree("is_read");
-- rollback DROP INDEX IF EXISTS "idx_notifications_is_read";

-- changeset liquibase-user:1757842686010-26 splitStatements:false
CREATE INDEX "idx_post_tags_post_id" ON "public"."post_tags" USING btree("post_id");
-- rollback DROP INDEX IF EXISTS "idx_post_tags_post_id";

-- changeset liquibase-user:1757842686010-27 splitStatements:false
CREATE INDEX "idx_post_tags_tag_id" ON "public"."post_tags" USING btree("tag_id");
-- rollback DROP INDEX IF EXISTS "idx_post_tags_tag_id";
