-- liquibase formatted sql

-- changeset liquibase-user:1757842702981-21 splitStatements:false
CREATE TABLE "public"."settings" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "key" VARCHAR(100) NOT NULL, "value" TEXT, "description" TEXT, "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), CONSTRAINT "settings_pkey" PRIMARY KEY ("id"));
-- rollback DROP TABLE IF EXISTS "settings";

-- changeset liquibase-user:1757842702981-22 splitStatements:false
CREATE TABLE "public"."notifications" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "user_id" INTEGER, "title" VARCHAR(200) NOT NULL, "message" TEXT, "type" VARCHAR(50) DEFAULT 'info', "is_read" BOOLEAN DEFAULT FALSE, "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), CONSTRAINT "notifications_pkey" PRIMARY KEY ("id"));
-- rollback DROP TABLE IF EXISTS "notifications";

-- changeset liquibase-user:1757842702981-25 splitStatements:false
ALTER TABLE "public"."settings" ADD CONSTRAINT "settings_key_key" UNIQUE ("key");
-- rollback -- Rollback: DROP CONSTRAINT "settings_key_key" from "settings"
-- Note: Skipped due to PostgreSQL limitations with IF EXISTS for constraints

-- changeset liquibase-user:1757842702981-28 splitStatements:false
ALTER TABLE "public"."user_profiles" ADD "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL;
-- rollback -- Empty rollback (manual intervention required)

-- changeset liquibase-user:1757842702981-29 splitStatements:false
ALTER TABLE "public"."tags" ADD "description" TEXT;
-- rollback -- Empty rollback (manual intervention required)

-- changeset liquibase-user:1757842702981-30 splitStatements:false
ALTER TABLE "public"."users" ADD "middle_name" VARCHAR(50);
-- rollback -- Empty rollback (manual intervention required)

-- changeset liquibase-user:1757842702981-31 splitStatements:false
ALTER TABLE "public"."posts" ADD "tags" TEXT;
-- rollback -- Empty rollback (manual intervention required)

-- changeset liquibase-user:1757842702981-32 splitStatements:false
ALTER TABLE "public"."notifications" ADD CONSTRAINT "notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- rollback -- Rollback: DROP CONSTRAINT "notifications_user_id_fkey" from "notifications"
-- Note: Skipped due to PostgreSQL limitations with IF EXISTS for constraints

-- changeset liquibase-user:1757842702981-2 splitStatements:false
ALTER TABLE "public"."comments" ADD CONSTRAINT "comments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- rollback -- Rollback: DROP CONSTRAINT "comments_user_id_fkey" from "comments"
-- Note: Skipped due to PostgreSQL limitations with IF EXISTS for constraints

-- changeset liquibase-user:1757842702981-20 splitStatements:false
ALTER TABLE "public"."user_profiles" ADD CONSTRAINT "user_profiles_pkey" PRIMARY KEY ("id");
-- rollback -- Rollback: DROP CONSTRAINT "user_profiles_pkey" from "user_profiles"
-- Note: Skipped due to PostgreSQL limitations with IF EXISTS for constraints

-- changeset liquibase-user:1757842702981-23 splitStatements:false
CREATE INDEX "idx_users_status" ON "public"."users" USING btree("status");
-- rollback DROP INDEX IF EXISTS "idx_users_status";

-- changeset liquibase-user:1757842702981-24 splitStatements:false
CREATE INDEX "idx_categories_name" ON "public"."categories" USING btree("name");
-- rollback DROP INDEX IF EXISTS "idx_categories_name";

-- changeset liquibase-user:1757842702981-26 splitStatements:false
CREATE INDEX "idx_notifications_user_id" ON "public"."notifications" USING btree("user_id");
-- rollback DROP INDEX IF EXISTS "idx_notifications_user_id";

-- changeset liquibase-user:1757842702981-27 splitStatements:false
CREATE INDEX "idx_notifications_is_read" ON "public"."notifications" USING btree("is_read");
-- rollback DROP INDEX IF EXISTS "idx_notifications_is_read";

-- changeset liquibase-user:1757842702981-1 splitStatements:false
ALTER TABLE "public"."comments" DROP CONSTRAINT "comments_user_id_fkey";
-- rollback -- Rollback for DROP CONSTRAINT comments_user_id_fkey requires original constraint definition

-- changeset liquibase-user:1757842702981-33 splitStatements:false
DROP INDEX "public"."idx_categories_is_active";
-- rollback -- Rollback for DROP INDEX requires original index definition

-- changeset liquibase-user:1757842702981-34 splitStatements:false
DROP INDEX "public"."idx_comments_created_at";
-- rollback -- Rollback for DROP INDEX requires original index definition

-- changeset liquibase-user:1757842702981-35 splitStatements:false
DROP INDEX "public"."idx_posts_created_at";
-- rollback -- Rollback for DROP INDEX requires original index definition

-- changeset liquibase-user:1757842702981-3 splitStatements:false
ALTER TABLE "public"."user_profiles" ALTER COLUMN "avatar_url" TYPE VARCHAR(255) USING ("avatar_url"::VARCHAR(255));
-- rollback -- Empty rollback (manual intervention required)

-- changeset liquibase-user:1757842702981-4 splitStatements:false
ALTER TABLE "public"."categories" ALTER COLUMN  "created_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "categories" ALTER COLUMN "created_at" DROP DEFAULT;

-- changeset liquibase-user:1757842702981-5 splitStatements:false
ALTER TABLE "public"."comments" ALTER COLUMN  "created_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "comments" ALTER COLUMN "created_at" DROP DEFAULT;

-- changeset liquibase-user:1757842702981-6 splitStatements:false
ALTER TABLE "public"."posts" ALTER COLUMN  "created_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "posts" ALTER COLUMN "created_at" DROP DEFAULT;

-- changeset liquibase-user:1757842702981-7 splitStatements:false
ALTER TABLE "public"."tags" ALTER COLUMN  "created_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "tags" ALTER COLUMN "created_at" DROP DEFAULT;

-- changeset liquibase-user:1757842702981-8 splitStatements:false
ALTER TABLE "public"."user_profiles" ALTER COLUMN  "created_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "user_profiles" ALTER COLUMN "created_at" DROP DEFAULT;

-- changeset liquibase-user:1757842702981-9 splitStatements:false
ALTER TABLE "public"."users" ALTER COLUMN  "created_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "users" ALTER COLUMN "created_at" DROP DEFAULT;

-- changeset liquibase-user:1757842702981-10 splitStatements:false
ALTER TABLE "public"."comments" ALTER COLUMN  "status" SET DEFAULT 'approved';
-- rollback ALTER TABLE "comments" ALTER COLUMN "status" DROP DEFAULT;

-- changeset liquibase-user:1757842702981-11 splitStatements:false
ALTER TABLE "public"."categories" ALTER COLUMN  "updated_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "categories" ALTER COLUMN "updated_at" DROP DEFAULT;

-- changeset liquibase-user:1757842702981-12 splitStatements:false
ALTER TABLE "public"."comments" ALTER COLUMN  "updated_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "comments" ALTER COLUMN "updated_at" DROP DEFAULT;

-- changeset liquibase-user:1757842702981-13 splitStatements:false
ALTER TABLE "public"."posts" ALTER COLUMN  "updated_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "posts" ALTER COLUMN "updated_at" DROP DEFAULT;

-- changeset liquibase-user:1757842702981-14 splitStatements:false
ALTER TABLE "public"."tags" ALTER COLUMN  "updated_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "tags" ALTER COLUMN "updated_at" DROP DEFAULT;

-- changeset liquibase-user:1757842702981-15 splitStatements:false
ALTER TABLE "public"."user_profiles" ALTER COLUMN  "updated_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "user_profiles" ALTER COLUMN "updated_at" DROP DEFAULT;

-- changeset liquibase-user:1757842702981-16 splitStatements:false
ALTER TABLE "public"."users" ALTER COLUMN  "updated_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "users" ALTER COLUMN "updated_at" DROP DEFAULT;

-- changeset liquibase-user:1757842702981-17 splitStatements:false
ALTER TABLE "public"."user_profiles" ALTER COLUMN  "user_id" DROP NOT NULL;
-- rollback -- Empty rollback (manual intervention required)

-- changeset liquibase-user:1757842702981-18 splitStatements:false
ALTER TABLE "public"."user_profiles" ALTER COLUMN "website" TYPE VARCHAR(255) USING ("website"::VARCHAR(255));
-- rollback -- Empty rollback (manual intervention required)

-- changeset liquibase-user:1757842702981-19 splitStatements:false
DO $$ DECLARE constraint_name varchar;
-- rollback -- Empty rollback (manual intervention required)
BEGIN
  SELECT tc.CONSTRAINT_NAME into strict constraint_name
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
    WHERE CONSTRAINT_TYPE = 'PRIMARY KEY'
      AND TABLE_NAME = 'user_profiles' AND TABLE_SCHEMA = 'public';
    EXECUTE 'alter table "public"."user_profiles" drop constraint "' || constraint_name || '"';
END $$;
