-- liquibase formatted sql

-- changeset liquibase-user:1757714029789-13 splitStatements:false
CREATE TABLE "public"."user_sessions" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "user_id" INTEGER, "session_token" VARCHAR(255) NOT NULL, "expires_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), CONSTRAINT "user_sessions_pkey" PRIMARY KEY ("id"));
-- rollback DROP TABLE IF EXISTS "public".user_sessions;

-- changeset liquibase-user:1757714029789-18 splitStatements:false
ALTER TABLE "public"."user_sessions" ADD CONSTRAINT "user_sessions_session_token_key" UNIQUE ("session_token");
-- rollback ALTER TABLE "public".user_sessions DROP COLUMN IF EXISTS "user_sessions_session_token_key";

-- changeset liquibase-user:1757714029789-19 splitStatements:false
ALTER TABLE "public"."users" ADD "phone" VARCHAR(20);
-- rollback ALTER TABLE "public".users DROP COLUMN IF EXISTS "phone";

-- changeset liquibase-user:1757714029789-20 splitStatements:false
ALTER TABLE "public"."users" ADD "last_login" TIMESTAMP WITHOUT TIME ZONE;
-- rollback ALTER TABLE "public".users DROP COLUMN IF EXISTS "last_login";

-- changeset liquibase-user:1757714029789-21 splitStatements:false
ALTER TABLE "public"."posts" ADD "view_count" INTEGER DEFAULT 0;
-- rollback ALTER TABLE "public".posts DROP COLUMN IF EXISTS "view_count";

-- changeset liquibase-user:1757714029789-22 splitStatements:false
ALTER TABLE "public"."posts" ADD "featured" BOOLEAN DEFAULT FALSE;
-- rollback ALTER TABLE "public".posts DROP COLUMN IF EXISTS "featured";

-- changeset liquibase-user:1757714029789-23 splitStatements:false
ALTER TABLE "public"."user_sessions" ADD CONSTRAINT "user_sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- rollback ALTER TABLE "public".user_sessions DROP COLUMN IF EXISTS "user_sessions_user_id_fkey";

-- changeset liquibase-user:1757714029789-14 splitStatements:false
CREATE INDEX "idx_posts_featured" ON "public"."posts" USING btree("featured");
-- rollback DROP INDEX IF EXISTS "idx_posts_featured";

-- changeset liquibase-user:1757714029789-15 splitStatements:false
CREATE INDEX "idx_posts_view_count" ON "public"."posts" USING btree("view_count");
-- rollback DROP INDEX IF EXISTS "idx_posts_view_count";

-- changeset liquibase-user:1757714029789-16 splitStatements:false
CREATE INDEX "idx_user_sessions_user_id" ON "public"."user_sessions" USING btree("user_id");
-- rollback DROP INDEX IF EXISTS "idx_user_sessions_user_id";

-- changeset liquibase-user:1757714029789-17 splitStatements:false
CREATE INDEX "idx_user_sessions_expires_at" ON "public"."user_sessions" USING btree("expires_at");
-- rollback DROP INDEX IF EXISTS "idx_user_sessions_expires_at";

-- changeset liquibase-user:1757714029789-1 splitStatements:false
ALTER TABLE "public"."categories" ALTER COLUMN  "created_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "public".categories ALTER COLUMN "created_at" DROP DEFAULT;

-- changeset liquibase-user:1757714029789-2 splitStatements:false
ALTER TABLE "public"."comments" ALTER COLUMN  "created_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "public".comments ALTER COLUMN "created_at" DROP DEFAULT;

-- changeset liquibase-user:1757714029789-3 splitStatements:false
ALTER TABLE "public"."posts" ALTER COLUMN  "created_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "public".posts ALTER COLUMN "created_at" DROP DEFAULT;

-- changeset liquibase-user:1757714029789-4 splitStatements:false
ALTER TABLE "public"."tags" ALTER COLUMN  "created_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "public".tags ALTER COLUMN "created_at" DROP DEFAULT;

-- changeset liquibase-user:1757714029789-5 splitStatements:false
ALTER TABLE "public"."user_profiles" ALTER COLUMN  "created_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "public".user_profiles ALTER COLUMN "created_at" DROP DEFAULT;

-- changeset liquibase-user:1757714029789-6 splitStatements:false
ALTER TABLE "public"."users" ALTER COLUMN  "created_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "public".users ALTER COLUMN "created_at" DROP DEFAULT;

-- changeset liquibase-user:1757714029789-7 splitStatements:false
ALTER TABLE "public"."categories" ALTER COLUMN  "updated_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "public".categories ALTER COLUMN "updated_at" DROP DEFAULT;

-- changeset liquibase-user:1757714029789-8 splitStatements:false
ALTER TABLE "public"."comments" ALTER COLUMN  "updated_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "public".comments ALTER COLUMN "updated_at" DROP DEFAULT;

-- changeset liquibase-user:1757714029789-9 splitStatements:false
ALTER TABLE "public"."posts" ALTER COLUMN  "updated_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "public".posts ALTER COLUMN "updated_at" DROP DEFAULT;

-- changeset liquibase-user:1757714029789-10 splitStatements:false
ALTER TABLE "public"."tags" ALTER COLUMN  "updated_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "public".tags ALTER COLUMN "updated_at" DROP DEFAULT;

-- changeset liquibase-user:1757714029789-11 splitStatements:false
ALTER TABLE "public"."user_profiles" ALTER COLUMN  "updated_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "public".user_profiles ALTER COLUMN "updated_at" DROP DEFAULT;

-- changeset liquibase-user:1757714029789-12 splitStatements:false
ALTER TABLE "public"."users" ALTER COLUMN  "updated_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "public".users ALTER COLUMN "updated_at" DROP DEFAULT;
