-- liquibase formatted sql

-- changeset liquibase-user:1757842660182-1 splitStatements:false
CREATE TABLE "public"."user_sessions" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "user_id" INTEGER, "session_token" VARCHAR(255) NOT NULL, "expires_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), CONSTRAINT "user_sessions_pkey" PRIMARY KEY ("id"));
-- rollback DROP TABLE IF EXISTS "user_sessions";

-- changeset liquibase-user:1757842660182-6 splitStatements:false
ALTER TABLE "public"."user_sessions" ADD CONSTRAINT "user_sessions_session_token_key" UNIQUE ("session_token");
-- rollback -- Rollback: DROP CONSTRAINT "user_sessions_session_token_key" from "user_sessions"
-- Note: Skipped due to PostgreSQL limitations with IF EXISTS for constraints

-- changeset liquibase-user:1757842660182-7 splitStatements:false
ALTER TABLE "public"."users" ADD "phone" VARCHAR(20);
-- rollback -- Empty rollback (manual intervention required)

-- changeset liquibase-user:1757842660182-8 splitStatements:false
ALTER TABLE "public"."users" ADD "last_login" TIMESTAMP WITHOUT TIME ZONE;
-- rollback -- Empty rollback (manual intervention required)

-- changeset liquibase-user:1757842660182-9 splitStatements:false
ALTER TABLE "public"."posts" ADD "view_count" INTEGER DEFAULT 0;
-- rollback -- Empty rollback (manual intervention required)

-- changeset liquibase-user:1757842660182-10 splitStatements:false
ALTER TABLE "public"."posts" ADD "featured" BOOLEAN DEFAULT FALSE;
-- rollback -- Empty rollback (manual intervention required)

-- changeset liquibase-user:1757842660182-11 splitStatements:false
ALTER TABLE "public"."user_sessions" ADD CONSTRAINT "user_sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- rollback -- Rollback: DROP CONSTRAINT "user_sessions_user_id_fkey" from "user_sessions"
-- Note: Skipped due to PostgreSQL limitations with IF EXISTS for constraints

-- changeset liquibase-user:1757842660182-2 splitStatements:false
CREATE INDEX "idx_posts_featured" ON "public"."posts" USING btree("featured");
-- rollback DROP INDEX IF EXISTS "idx_posts_featured";

-- changeset liquibase-user:1757842660182-3 splitStatements:false
CREATE INDEX "idx_posts_view_count" ON "public"."posts" USING btree("view_count");
-- rollback DROP INDEX IF EXISTS "idx_posts_view_count";

-- changeset liquibase-user:1757842660182-4 splitStatements:false
CREATE INDEX "idx_user_sessions_user_id" ON "public"."user_sessions" USING btree("user_id");
-- rollback DROP INDEX IF EXISTS "idx_user_sessions_user_id";

-- changeset liquibase-user:1757842660182-5 splitStatements:false
CREATE INDEX "idx_user_sessions_expires_at" ON "public"."user_sessions" USING btree("expires_at");
-- rollback DROP INDEX IF EXISTS "idx_user_sessions_expires_at";
