-- liquibase formatted sql

-- changeset root:1757711929614-13 splitStatements:false
CREATE TABLE "public"."user_sessions" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "user_id" INTEGER, "session_token" VARCHAR(255) NOT NULL, "expires_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), CONSTRAINT "user_sessions_pkey" PRIMARY KEY ("id"));
-- rollback DROP TABLE IF EXISTS "public".user_sessions;



-- changeset root:1757711929614-18 splitStatements:false
ALTER TABLE "public"."user_sessions" ADD CONSTRAINT "user_sessions_session_token_key" UNIQUE ("session_token");
-- rollback ALTER TABLE "public".user_sessions DROP CONSTRAINT IF EXISTS "user_sessions_session_token_key";



-- changeset root:1757711929614-19 splitStatements:false
ALTER TABLE "public"."users" ADD "phone" VARCHAR(20);
-- rollback -- Empty rollback (manual intervention required)



-- changeset root:1757711929614-20 splitStatements:false
ALTER TABLE "public"."users" ADD "last_login" TIMESTAMP WITHOUT TIME ZONE;
-- rollback -- Empty rollback (manual intervention required)



-- changeset root:1757711929614-21 splitStatements:false
ALTER TABLE "public"."posts" ADD "view_count" INTEGER DEFAULT 0;
-- rollback -- Empty rollback (manual intervention required)



-- changeset root:1757711929614-22 splitStatements:false
ALTER TABLE "public"."posts" ADD "featured" BOOLEAN DEFAULT FALSE;
-- rollback -- Empty rollback (manual intervention required)



-- changeset root:1757711929614-23 splitStatements:false
ALTER TABLE "public"."user_sessions" ADD CONSTRAINT "user_sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- rollback ALTER TABLE "public".user_sessions DROP CONSTRAINT IF EXISTS "user_sessions_user_id_fkey";



-- changeset root:1757711929614-14 splitStatements:false
CREATE INDEX "idx_posts_featured" ON "public"."posts" USING btree("featured");
-- rollback DROP INDEX IF EXISTS "idx_posts_featured";



-- changeset root:1757711929614-15 splitStatements:false
CREATE INDEX "idx_posts_view_count" ON "public"."posts" USING btree("view_count");
-- rollback DROP INDEX IF EXISTS "idx_posts_view_count";



-- changeset root:1757711929614-16 splitStatements:false
CREATE INDEX "idx_user_sessions_user_id" ON "public"."user_sessions" USING btree("user_id");
-- rollback DROP INDEX IF EXISTS "idx_user_sessions_user_id";



-- changeset root:1757711929614-17 splitStatements:false
CREATE INDEX "idx_user_sessions_expires_at" ON "public"."user_sessions" USING btree("expires_at");
-- rollback DROP INDEX IF EXISTS "idx_user_sessions_expires_at";



-- changeset root:1757711929614-1 splitStatements:false
ALTER TABLE "public"."categories" ALTER COLUMN  "created_at" SET DEFAULT NOW();
-- rollback -- Empty rollback (manual intervention required)



-- changeset root:1757711929614-2 splitStatements:false
ALTER TABLE "public"."comments" ALTER COLUMN  "created_at" SET DEFAULT NOW();
-- rollback -- Empty rollback (manual intervention required)



-- changeset root:1757711929614-3 splitStatements:false
ALTER TABLE "public"."posts" ALTER COLUMN  "created_at" SET DEFAULT NOW();
-- rollback -- Empty rollback (manual intervention required)



-- changeset root:1757711929614-4 splitStatements:false
ALTER TABLE "public"."tags" ALTER COLUMN  "created_at" SET DEFAULT NOW();
-- rollback -- Empty rollback (manual intervention required)



-- changeset root:1757711929614-5 splitStatements:false
ALTER TABLE "public"."user_profiles" ALTER COLUMN  "created_at" SET DEFAULT NOW();
-- rollback -- Empty rollback (manual intervention required)



-- changeset root:1757711929614-6 splitStatements:false
ALTER TABLE "public"."users" ALTER COLUMN  "created_at" SET DEFAULT NOW();
-- rollback -- Empty rollback (manual intervention required)



-- changeset root:1757711929614-7 splitStatements:false
ALTER TABLE "public"."categories" ALTER COLUMN  "updated_at" SET DEFAULT NOW();
-- rollback -- Empty rollback (manual intervention required)



-- changeset root:1757711929614-8 splitStatements:false
ALTER TABLE "public"."comments" ALTER COLUMN  "updated_at" SET DEFAULT NOW();
-- rollback -- Empty rollback (manual intervention required)



-- changeset root:1757711929614-9 splitStatements:false
ALTER TABLE "public"."posts" ALTER COLUMN  "updated_at" SET DEFAULT NOW();
-- rollback -- Empty rollback (manual intervention required)



-- changeset root:1757711929614-10 splitStatements:false
ALTER TABLE "public"."tags" ALTER COLUMN  "updated_at" SET DEFAULT NOW();
-- rollback -- Empty rollback (manual intervention required)



-- changeset root:1757711929614-11 splitStatements:false
ALTER TABLE "public"."user_profiles" ALTER COLUMN  "updated_at" SET DEFAULT NOW();
-- rollback -- Empty rollback (manual intervention required)



-- changeset root:1757711929614-12 splitStatements:false
ALTER TABLE "public"."users" ALTER COLUMN  "updated_at" SET DEFAULT NOW();
-- rollback -- Empty rollback (manual intervention required)



