-- liquibase formatted sql

-- changeset root:1757713093142-13 splitStatements:false
CREATE TABLE "public"."user_sessions" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "user_id" INTEGER, "session_token" VARCHAR(255) NOT NULL, "expires_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL, "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), CONSTRAINT "user_sessions_pkey" PRIMARY KEY ("id"));
-- rollback DROP TABLE IF EXISTS "public".user_sessions;



-- changeset root:1757713093142-18 splitStatements:false
ALTER TABLE "public"."user_sessions" ADD CONSTRAINT "user_sessions_session_token_key" UNIQUE ("session_token");
-- rollback ALTER TABLE "public".user_sessions DROP COLUMN IF EXISTS "user_sessions_session_token_key";



-- changeset root:1757713093142-19 splitStatements:false
ALTER TABLE "public"."users" ADD "phone" VARCHAR(20);
-- rollback ALTER TABLE "public".users DROP COLUMN IF EXISTS "phone";



-- changeset root:1757713093142-20 splitStatements:false
ALTER TABLE "public"."users" ADD "last_login" TIMESTAMP WITHOUT TIME ZONE;
-- rollback ALTER TABLE "public".users DROP COLUMN IF EXISTS "last_login";



-- changeset root:1757713093142-21 splitStatements:false
ALTER TABLE "public"."posts" ADD "view_count" INTEGER DEFAULT 0;
-- rollback ALTER TABLE "public".posts DROP COLUMN IF EXISTS "view_count";



-- changeset root:1757713093142-22 splitStatements:false
ALTER TABLE "public"."posts" ADD "featured" BOOLEAN DEFAULT FALSE;
-- rollback ALTER TABLE "public".posts DROP COLUMN IF EXISTS "featured";



-- changeset root:1757713093142-23 splitStatements:false
ALTER TABLE "public"."user_sessions" ADD CONSTRAINT "user_sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- rollback ALTER TABLE "public".user_sessions DROP COLUMN IF EXISTS "user_sessions_user_id_fkey";



-- changeset root:1757713093142-14 splitStatements:false
CREATE INDEX "idx_posts_featured" ON "public"."posts" USING btree("featured");
-- rollback DROP INDEX IF EXISTS "idx_posts_featured";



-- changeset root:1757713093142-15 splitStatements:false
CREATE INDEX "idx_posts_view_count" ON "public"."posts" USING btree("view_count");
-- rollback DROP INDEX IF EXISTS "idx_posts_view_count";



-- changeset root:1757713093142-16 splitStatements:false
CREATE INDEX "idx_user_sessions_user_id" ON "public"."user_sessions" USING btree("user_id");
-- rollback DROP INDEX IF EXISTS "idx_user_sessions_user_id";



-- changeset root:1757713093142-17 splitStatements:false
CREATE INDEX "idx_user_sessions_expires_at" ON "public"."user_sessions" USING btree("expires_at");
-- rollback DROP INDEX IF EXISTS "idx_user_sessions_expires_at";



-- changeset root:1757713093142-1 splitStatements:false
ALTER TABLE "public"."categories" ALTER COLUMN  "created_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "public".categories ALTER COLUMN "created_at" DROP DEFAULT;



-- changeset root:1757713093142-2 splitStatements:false
ALTER TABLE "public"."comments" ALTER COLUMN  "created_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "public".comments ALTER COLUMN "created_at" DROP DEFAULT;



-- changeset root:1757713093142-3 splitStatements:false
ALTER TABLE "public"."posts" ALTER COLUMN  "created_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "public".posts ALTER COLUMN "created_at" DROP DEFAULT;



-- changeset root:1757713093142-4 splitStatements:false
ALTER TABLE "public"."tags" ALTER COLUMN  "created_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "public".tags ALTER COLUMN "created_at" DROP DEFAULT;



-- changeset root:1757713093142-5 splitStatements:false
ALTER TABLE "public"."user_profiles" ALTER COLUMN  "created_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "public".user_profiles ALTER COLUMN "created_at" DROP DEFAULT;



-- changeset root:1757713093142-6 splitStatements:false
ALTER TABLE "public"."users" ALTER COLUMN  "created_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "public".users ALTER COLUMN "created_at" DROP DEFAULT;



-- changeset root:1757713093142-7 splitStatements:false
ALTER TABLE "public"."categories" ALTER COLUMN  "updated_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "public".categories ALTER COLUMN "updated_at" DROP DEFAULT;



-- changeset root:1757713093142-8 splitStatements:false
ALTER TABLE "public"."comments" ALTER COLUMN  "updated_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "public".comments ALTER COLUMN "updated_at" DROP DEFAULT;



-- changeset root:1757713093142-9 splitStatements:false
ALTER TABLE "public"."posts" ALTER COLUMN  "updated_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "public".posts ALTER COLUMN "updated_at" DROP DEFAULT;



-- changeset root:1757713093142-10 splitStatements:false
ALTER TABLE "public"."tags" ALTER COLUMN  "updated_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "public".tags ALTER COLUMN "updated_at" DROP DEFAULT;



-- changeset root:1757713093142-11 splitStatements:false
ALTER TABLE "public"."user_profiles" ALTER COLUMN  "updated_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "public".user_profiles ALTER COLUMN "updated_at" DROP DEFAULT;



-- changeset root:1757713093142-12 splitStatements:false
ALTER TABLE "public"."users" ALTER COLUMN  "updated_at" SET DEFAULT NOW();
-- rollback ALTER TABLE "public".users ALTER COLUMN "updated_at" DROP DEFAULT;



