-- liquibase formatted sql

-- changeset liquibase-user:1757765668057-1 splitStatements:false
CREATE TABLE "public"."users" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "username" VARCHAR(50) NOT NULL, "email" VARCHAR(100) NOT NULL, "first_name" VARCHAR(50), "last_name" VARCHAR(50), "status" VARCHAR(20) DEFAULT 'active', "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), CONSTRAINT "users_pkey" PRIMARY KEY ("id"));
-- rollback DROP TABLE IF EXISTS "users";

-- changeset liquibase-user:1757765668057-2 splitStatements:false
CREATE TABLE "public"."categories" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR(100) NOT NULL, "description" TEXT, "parent_id" INTEGER, "is_active" BOOLEAN DEFAULT TRUE, "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), CONSTRAINT "categories_pkey" PRIMARY KEY ("id"));
-- rollback DROP TABLE IF EXISTS "categories";

-- changeset liquibase-user:1757765668057-3 splitStatements:false
CREATE TABLE "public"."posts" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "user_id" INTEGER, "category_id" INTEGER, "title" VARCHAR(200) NOT NULL, "slug" VARCHAR(250) NOT NULL, "content" TEXT, "excerpt" TEXT, "status" VARCHAR(20) DEFAULT 'draft', "published_at" TIMESTAMP WITHOUT TIME ZONE, "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), CONSTRAINT "posts_pkey" PRIMARY KEY ("id"));
-- rollback DROP TABLE IF EXISTS "posts";

-- changeset liquibase-user:1757765668057-4 splitStatements:false
CREATE TABLE "public"."tags" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR(50) NOT NULL, "color" VARCHAR(7) DEFAULT '#007bff', "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), CONSTRAINT "tags_pkey" PRIMARY KEY ("id"));
-- rollback DROP TABLE IF EXISTS "tags";

-- changeset liquibase-user:1757765668057-5 splitStatements:false
CREATE TABLE "public"."comments" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "post_id" INTEGER, "user_id" INTEGER, "parent_id" INTEGER, "content" TEXT NOT NULL, "status" VARCHAR(20) DEFAULT 'pending', "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), CONSTRAINT "comments_pkey" PRIMARY KEY ("id"));
-- rollback DROP TABLE IF EXISTS "comments";

-- changeset liquibase-user:1757765668057-6 splitStatements:false
CREATE TABLE "public"."user_profiles" ("user_id" INTEGER NOT NULL, "bio" TEXT, "avatar_url" VARCHAR(500), "website" VARCHAR(200), "location" VARCHAR(100), "birth_date" date, "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(), CONSTRAINT "user_profiles_pkey" PRIMARY KEY ("user_id"));
-- rollback DROP TABLE IF EXISTS "user_profiles";

-- changeset liquibase-user:1757765668057-7 splitStatements:false
CREATE TABLE "public"."post_tags" ("post_id" INTEGER NOT NULL, "tag_id" INTEGER NOT NULL, CONSTRAINT "post_tags_pkey" PRIMARY KEY ("post_id", "tag_id"));
-- rollback DROP TABLE IF EXISTS "post_tags";

-- changeset liquibase-user:1757765668057-8 splitStatements:false
ALTER TABLE "public"."users" ADD CONSTRAINT "users_email_key" UNIQUE ("email");
-- rollback -- Rollback: DROP CONSTRAINT "users_email_key" from "users"
-- Note: Skipped due to PostgreSQL limitations with IF EXISTS for constraints

-- changeset liquibase-user:1757765668057-9 splitStatements:false
ALTER TABLE "public"."users" ADD CONSTRAINT "users_username_key" UNIQUE ("username");
-- rollback -- Rollback: DROP CONSTRAINT "users_username_key" from "users"
-- Note: Skipped due to PostgreSQL limitations with IF EXISTS for constraints

-- changeset liquibase-user:1757765668057-10 splitStatements:false
CREATE INDEX "idx_categories_parent_id" ON "public"."categories" USING btree("parent_id");
-- rollback DROP INDEX IF EXISTS "idx_categories_parent_id";

-- changeset liquibase-user:1757765668057-11 splitStatements:false
CREATE INDEX "idx_categories_is_active" ON "public"."categories" USING btree("is_active");
-- rollback DROP INDEX IF EXISTS "idx_categories_is_active";

-- changeset liquibase-user:1757765668057-12 splitStatements:false
CREATE INDEX "idx_posts_user_id" ON "public"."posts" USING btree("user_id");
-- rollback DROP INDEX IF EXISTS "idx_posts_user_id";

-- changeset liquibase-user:1757765668057-13 splitStatements:false
CREATE INDEX "idx_posts_category_id" ON "public"."posts" USING btree("category_id");
-- rollback DROP INDEX IF EXISTS "idx_posts_category_id";

-- changeset liquibase-user:1757765668057-14 splitStatements:false
CREATE INDEX "idx_posts_status" ON "public"."posts" USING btree("status");
-- rollback DROP INDEX IF EXISTS "idx_posts_status";

-- changeset liquibase-user:1757765668057-15 splitStatements:false
CREATE INDEX "idx_posts_published_at" ON "public"."posts" USING btree("published_at");
-- rollback DROP INDEX IF EXISTS "idx_posts_published_at";

-- changeset liquibase-user:1757765668057-16 splitStatements:false
CREATE INDEX "idx_posts_created_at" ON "public"."posts" USING btree("created_at");
-- rollback DROP INDEX IF EXISTS "idx_posts_created_at";

-- changeset liquibase-user:1757765668057-17 splitStatements:false
ALTER TABLE "public"."posts" ADD CONSTRAINT "posts_slug_key" UNIQUE ("slug");
-- rollback -- Rollback: DROP CONSTRAINT "posts_slug_key" from "posts"
-- Note: Skipped due to PostgreSQL limitations with IF EXISTS for constraints

-- changeset liquibase-user:1757765668057-18 splitStatements:false
ALTER TABLE "public"."tags" ADD CONSTRAINT "tags_name_key" UNIQUE ("name");
-- rollback -- Rollback: DROP CONSTRAINT "tags_name_key" from "tags"
-- Note: Skipped due to PostgreSQL limitations with IF EXISTS for constraints

-- changeset liquibase-user:1757765668057-19 splitStatements:false
CREATE INDEX "idx_comments_post_id" ON "public"."comments" USING btree("post_id");
-- rollback DROP INDEX IF EXISTS "idx_comments_post_id";

-- changeset liquibase-user:1757765668057-20 splitStatements:false
CREATE INDEX "idx_comments_user_id" ON "public"."comments" USING btree("user_id");
-- rollback DROP INDEX IF EXISTS "idx_comments_user_id";

-- changeset liquibase-user:1757765668057-21 splitStatements:false
CREATE INDEX "idx_comments_parent_id" ON "public"."comments" USING btree("parent_id");
-- rollback DROP INDEX IF EXISTS "idx_comments_parent_id";

-- changeset liquibase-user:1757765668057-22 splitStatements:false
CREATE INDEX "idx_comments_status" ON "public"."comments" USING btree("status");
-- rollback DROP INDEX IF EXISTS "idx_comments_status";

-- changeset liquibase-user:1757765668057-23 splitStatements:false
CREATE INDEX "idx_comments_created_at" ON "public"."comments" USING btree("created_at");
-- rollback DROP INDEX IF EXISTS "idx_comments_created_at";

-- changeset liquibase-user:1757765668057-24 splitStatements:false
CREATE INDEX "idx_post_tags_post_id" ON "public"."post_tags" USING btree("post_id");
-- rollback DROP INDEX IF EXISTS "idx_post_tags_post_id";

-- changeset liquibase-user:1757765668057-25 splitStatements:false
CREATE INDEX "idx_post_tags_tag_id" ON "public"."post_tags" USING btree("tag_id");
-- rollback DROP INDEX IF EXISTS "idx_post_tags_tag_id";

-- changeset liquibase-user:1757765668057-26 splitStatements:false
ALTER TABLE "public"."categories" ADD CONSTRAINT "categories_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "public"."categories" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- rollback -- Rollback: DROP CONSTRAINT "categories_parent_id_fkey" from "categories"
-- Note: Skipped due to PostgreSQL limitations with IF EXISTS for constraints

-- changeset liquibase-user:1757765668057-27 splitStatements:false
ALTER TABLE "public"."comments" ADD CONSTRAINT "comments_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "public"."comments" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- rollback -- Rollback: DROP CONSTRAINT "comments_parent_id_fkey" from "comments"
-- Note: Skipped due to PostgreSQL limitations with IF EXISTS for constraints

-- changeset liquibase-user:1757765668057-28 splitStatements:false
ALTER TABLE "public"."comments" ADD CONSTRAINT "comments_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "public"."posts" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- rollback -- Rollback: DROP CONSTRAINT "comments_post_id_fkey" from "comments"
-- Note: Skipped due to PostgreSQL limitations with IF EXISTS for constraints

-- changeset liquibase-user:1757765668057-29 splitStatements:false
ALTER TABLE "public"."comments" ADD CONSTRAINT "comments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- rollback -- Rollback: DROP CONSTRAINT "comments_user_id_fkey" from "comments"
-- Note: Skipped due to PostgreSQL limitations with IF EXISTS for constraints

-- changeset liquibase-user:1757765668057-30 splitStatements:false
ALTER TABLE "public"."post_tags" ADD CONSTRAINT "post_tags_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "public"."posts" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- rollback -- Rollback: DROP CONSTRAINT "post_tags_post_id_fkey" from "post_tags"
-- Note: Skipped due to PostgreSQL limitations with IF EXISTS for constraints

-- changeset liquibase-user:1757765668057-31 splitStatements:false
ALTER TABLE "public"."post_tags" ADD CONSTRAINT "post_tags_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "public"."tags" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- rollback -- Rollback: DROP CONSTRAINT "post_tags_tag_id_fkey" from "post_tags"
-- Note: Skipped due to PostgreSQL limitations with IF EXISTS for constraints

-- changeset liquibase-user:1757765668057-32 splitStatements:false
ALTER TABLE "public"."posts" ADD CONSTRAINT "posts_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "public"."categories" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- rollback -- Rollback: DROP CONSTRAINT "posts_category_id_fkey" from "posts"
-- Note: Skipped due to PostgreSQL limitations with IF EXISTS for constraints

-- changeset liquibase-user:1757765668057-33 splitStatements:false
ALTER TABLE "public"."posts" ADD CONSTRAINT "posts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- rollback -- Rollback: DROP CONSTRAINT "posts_user_id_fkey" from "posts"
-- Note: Skipped due to PostgreSQL limitations with IF EXISTS for constraints

-- changeset liquibase-user:1757765668057-34 splitStatements:false
ALTER TABLE "public"."user_profiles" ADD CONSTRAINT "user_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- rollback -- Rollback: DROP CONSTRAINT "user_profiles_user_id_fkey" from "user_profiles"
-- Note: Skipped due to PostgreSQL limitations with IF EXISTS for constraints
